version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: taskflow
      POSTGRES_USER: taskflow
      POSTGRES_PASSWORD: taskflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  taskflow-api:
    build: 
      context: .
      dockerfile: Dockerfile
      target: api
    ports:
      - "8080:8080"
    environment:
      SERVER_ADDR: ":8080"
      REDIS_ADDR: "redis:6379"
      DATABASE_URL: "postgres://taskflow:taskflow@postgres:5432/taskflow?sslmode=disable"
    depends_on:
      - redis
      - postgres
    restart: unless-stopped

  taskflow-worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
    environment:
      WORKER_COUNT: "3"
      REDIS_ADDR: "redis:6379"
      DATABASE_URL: "postgres://taskflow:taskflow@postgres:5432/taskflow?sslmode=disable"
    depends_on:
      - redis
      - postgres
      - taskflow-api
    restart: unless-stopped
    scale: 2  # Run 2 worker instances

volumes:
  redis_data:
  postgres_data: